services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digital_hunter
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - .data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  
  api:
    build: ./api
    container_name: api
    environment:
      HOST: mysql
      PORT: "3306"
      USER: root
      PASSWORD: root
      DATABASE: digital_hunter
    depends_on:
      mysql:
        condition: service_healthy


volumes:
  mysql_data:
